name: Build and Deploy

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      # Build Go project to WASM
      - name: Build Go to WASM
        run: |
          cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" go_impl/
          cd go_impl
          GOOS=js GOARCH=wasm go build -o main.wasm

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: 'ui_web/package-lock.json'

      # Install dependencies and build UI project
      - name: Build UI project
        env:
          gh_repo: ${{ github.repository }}
        run: |
          cd ui_web
          npm install
          npm run build

      # Copy files to a single directory
      - name: Prepare hosting directory
        run: |
          mkdir -p gh_pages
          cp go_impl/wasm_exec.js gh_pages/
          cp go_impl/main.wasm gh_pages/
          cp -r ui_web/dist/* gh_pages/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gh_pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
